### ISSUE TITLE
Can't build the solution

### ISSUE THREAD

**Issue by jamescro** [jamesmontemagno/Office365-FiveMinuteMeeting#3]
I've downloaded the sample as a zip. When I try to build the solution, I get six instances of this error:

"The name 'BigTed' does not exist in the current context"

These are all ViewController files in the iOS project. I've tried adding a reference to BTProgressHUD.dll in the Components\btprogresshud-1.16\lib\ios folder, but that doesn't fix the problem.

**Comment by jamesmontemagno** [comment]
Have you tried to download and re-add the component? It has a specific version that needs to be added in.

**Comment by jamescro** [comment]
I re-added the component, and the iOS project builds now. Thanks!
